apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: gpu-allocation-
spec:
  serviceAccountName: argo-workflow
  entrypoint: main
  arguments:
    parameters:
    - name: secret
      value: argo-workflows-admin.service-account-token
    - name: argo-server-url
      value: http://argo-workflows-server.argo.svc.cluster.local:2746/api/v1/workflows
    - name: namespace
      value: default
    - name: gpus
      value: 1
    - name: workflow-name
      value: fantastic-tiger
  templates:
    - name: main
      steps:
      - - name: gpu-allocation
          template: create-wf
    - name: create-wf
      podSpecPatch: '{"containers":[{"name":"main", "resources":{"limits":{"nvidia.com/gpu": "{{workflow.parameters.gpus}}" }}}]}'
      script:
        image: badouralix/curl-jq:latest
        command:
          - sh
        source: >
          echo "GPU_UUID: $NVIDIA_VISIBLE_DEVICES / NODE_NAME: $NODE_NAME";
          WORKFLOW_UID=$(curl "{{workflow.parameters.argo-server-url}}/{{workflow.parameters.namespace}}/submit" \
            -fs \
            -H "Authorization: Bearer $ARGO_TOKEN" \
            -d '{
              "resourceKind": "WorkflowTemplate",
              "resourceName": "{{workflow.parameters.workflow-name}}",
              "parameters": [
                {
                  "name": "message",
                  "value": "called"
                }
              ]
            }' | jq -r '.metadata.name');
          echo "WORKFLOW_UID: $WORKFLOW_UID";

          echo "Watch $WORKFLOW_UID until it is finished";
          while true; do
            STATUS=$(curl --silent -X GET "{{workflow.parameters.argo-server-url}}/{{workflow.parameters.namespace}}/$WORKFLOW_UID" \
              -H "Authorization: Bearer $ARGO_TOKEN" \
              -H "Content-Type: application/json" \
            | jq -r '.status.phase');
            echo "Current status: $STATUS";

            if [ "$STATUS" == "Succeeded" ] || [ "$STATUS" == "Failed" ] || [ "$STATUS" == "Error" ]; then
              break
            fi
            sleep 3
          done;
          echo "Workflow $WORKFLOW_UID completed with status: $STATUS";
        env:
        - name: ARGO_TOKEN
          valueFrom:
            secretKeyRef:
              name: "{{workflow.parameters.secret}}"
              key: token
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
