apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: disable-mps-workflow-template
spec:
  ttlStrategy:
    secondsAfterCompletion: 3600
  serviceAccountName: argo-workflow
  entrypoint: main
  arguments:
    parameters:
    - name: gpu-uuids
    - name: node-name
  templates:
  - name: main
    steps:
    - - name: disable-mps
        template: disable-mps


  - name: disable-mps
    nodeSelector:
      kubernetes.io/hostname: "{{workflow.parameters.node-name}}"
    script:
      image: nvidia/cuda:12.1.0-base-ubuntu18.04
      env:
      - name: NVIDIA_VISIBLE_DEVICES
        value: "{{workflow.parameters.gpu-uuids}}"
      command: [sh, -c]
      source: |
        echo quit | nvidia-cuda-mps-control
        nvidia-smi -c DEFAULT
        echo "MPS disabled"
