apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: enable-mps-workflow-template
spec:
  ttlStrategy:
    secondsAfterCompletion: 3600
  serviceAccountName: argo-workflow
  entrypoint: main
  arguments:
    parameters:
    - name: gpu-uuids
    - name: node-name
  templates:
  - name: main
    steps:
    - - name: enable-mps
        template: enable-mps


  - name: enable-mps
    nodeSelector:
      kubernetes.io/hostname: "{{workflow.parameters.node-name}}"
    script:
      image: nvidia/cuda:12.1.0-base-ubuntu18.04
      securityContext:
        privileged: true
      env:
      - name: NVIDIA_VISIBLE_DEVICES
        value: "{{workflow.parameters.gpu-uuids}}"
      command: [sh]
      source: |
        echo "mps activation start"
        nvidia-smi -c EXCLUSIVE_PROCESS
        echo "set GPU $NVIDIA_VISIBLE_DEVICES mode as EXECLUSIVE_PROCESS"
        nvidia-cuda-mps-control -d
        echo "MPS enabled"
