apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: gpu-sharing-workflow-template
spec:
  ttlStrategy:
    secondsAfterCompletion: 3600
  serviceAccountName: argo-workflow
  entrypoint: main
  arguments:
    parameters:
    - name: gpu-uuids
      value: GPU-7e42023c-83da-f45d-8b7a-98d93dec657b
    - name: node-name
      value: minikube
  templates:
  - name: main
    dag:
      tasks:
      - name: step1
        template: load-test
      - name: step2
        template: load-test


  - name: load-test
    podSpecPatch: '{"hostIPC": true}'  # for MPS
    nodeSelector:
      kubernetes.io/hostname: "{{workflow.parameters.node-name}}"
    container:
      image: oguzpastirmaci/gpu-burn:latest
      command: ["./gpu_burn", "15"]
      env:
      - name: NVIDIA_VISIBLE_DEVICES
        value: "{{workflow.parameters.gpu-uuids}}"
