apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: mps-control-workflow-template
spec:
  ttlStrategy:
    secondsAfterCompletion: 3600
  serviceAccountName: argo-workflow
  entrypoint: main
  arguments:
    parameters:
    - name: gpu-uuids
    - name: node-name
  volumes:
  - name: nvidia-cuda-mps-control
    hostPath:
      path: /usr/bin/nvidia-cuda-mps-control
      type: File
  - name: nvidia-mps
    hostPath:
      path: /tmp/nvidia-mps
      type: DirectoryOrCreate
  templates:
  - name: main
    steps:
    - - name: enable-mps
        template: enable-mps
    - - name: wait
        template: wait
    - - name: disable-mps
        template: disable-mps


  - name: enable-mps
    nodeSelector:
      kubernetes.io/hostname: "{{workflow.parameters.node-name}}"
    script:
      image: nvidia/cuda:12.1.0-base-ubuntu18.04
      hostIPC: true
      securityContext:
        privileged: true
      volumeMounts:
      - name: nvidia-cuda-mps-control
        mountPath: /host/bin/nvidia-cuda-mps-control
      - name: nvidia-mps
        mountPath: /tmp/nvidia-mps
      env:
      - name: NVIDIA_VISIBLE_DEVICES
        value: "{{workflow.parameters.gpu-uuids}}"
      command: [sh]
      source: |
        echo "mps activation start"
        nvidia-smi -c EXCLUSIVE_PROCESS
        echo "set GPU $NVIDIA_VISIBLE_DEVICES mode as EXECLUSIVE_PROCESS"
        nvidia-cuda-mps-control -d
        echo "MPS enabled"
        ps -ef | grep mps

  - name: wait
    suspend: {}

  - name: disable-mps
    nodeSelector:
      kubernetes.io/hostname: "{{workflow.parameters.node-name}}"
    script:
      image: nvidia/cuda:12.1.0-base-ubuntu18.04
      hostIPC: true
      securityContext:
        privileged: true
      volumeMounts:
      - name: nvidia-cuda-mps-control
        mountPath: /host/bin/nvidia-cuda-mps-control
      - name: nvidia-mps
        mountPath: /tmp/nvidia-mps
      env:
      - name: NVIDIA_VISIBLE_DEVICES
        value: "{{workflow.parameters.gpu-uuids}}"
      command: [sh]
      source: |
        echo "mps deactivation start"
        echo quit | nvidia-cuda-mps-control
        echo "set GPU $NVIDIA_VISIBLE_DEVICES mode as DEFAULT"
        nvidia-smi -c DEFAULT
        echo "MPS disabled"
        ps -ef | grep mps
